[tool.black]
line-length = 127

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = [
  'ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning',
]
