name: lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint
        run: |
          poetry run ruff check mtpp tests
